language: android
jdk: oraclejdk8

env:
  global:
    - API_LEVEL=28
    - BUILD_TOOLS_VERSION=28.0.3

android:
  components:
    - tools
    - platform-tools
    - build-tools-$BUILD_TOOLS_VERSION
    - android-$API_LEVEL
    - sys-img-armeabi-v7a-android-27
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  - ./gradlew build

after_script:
  - echo no | avdmanager create avd --force -n emulatorApi27 -k "system-images;android-27;default;armeabi-v7a"
  - $ANDROID_HOME/emulator/emulator -avd emulatorApi27 -no-audio -no-window -no-skin &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - ./gradlew connectedCheck

before_install:
  - pip install --user codecov

after_success:
  - codecov